
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
include $(APPDIR)/Make.defs

ifeq ($(CONFIG_ZEPHYR_REPO_3_0_1), y)
    include $(APPDIR)/external/zblue/Makefile.3_0_1
else
    include $(APPDIR)/external/zblue/Makefile.default
endif
